import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportData {
  shopName: string;
  reportTitle: string;
  dateRange: string;
  stats: { label: string; value: string }[];
  products: { name: string; quantity: string; amount: string }[];
  payments: { type: string; amount: string }[];
}

interface BillData {
  shopName: string;
  shopPhone: string;
  shopAddress: string;
  customerName: string;
  customerPhone: string;
  customerAddress: string;
  items: { name: string; quantity: number; price: number; total: number }[];
  totalAmount: number;
  paidAmount: number;
  dueAmount: number;
  date: string;
}

// New Monthly Bill interface for Fixed Customers
interface MonthlyBillData {
  shopName: string;
  shopPhone: string;
  shopAddress: string;
  customerName: string;
  customerPhone: string;
  customerAddress: string;
  month: string; // e.g., "December 2024"
  previousBalance: number;
  deliveries: {
    date: string;
    items: { name: string; quantity: number; price: number; total: number }[];
    total: number;
    paidAtDelivery: number;
  }[];
  payments: {
    date: string;
    amount: number;
    mode: 'cash' | 'online';
  }[];
  monthlyTotal: number;
  totalPayments: number;
  balanceDue: number;
}

export function exportReportToPDF(data: ReportData) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(data.shopName || 'Dairy Management System', 105, 20, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(data.reportTitle, 105, 30, { align: 'center' });

  doc.setFontSize(11);
  doc.text(data.dateRange, 105, 38, { align: 'center' });

  // Summary Stats
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, 55);

  let yPos = 62;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  data.stats.forEach(stat => {
    doc.text(`${stat.label}: ${stat.value}`, 14, yPos);
    yPos += 7;
  });

  // Product Breakdown Table
  if (data.products.length > 0) {
    yPos += 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Product Breakdown', 14, yPos);

    autoTable(doc, {
      startY: yPos + 5,
      head: [['Product', 'Quantity', 'Amount']],
      body: data.products.map(p => [p.name, p.quantity, p.amount]),
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  // Payment Breakdown Table
  if (yPos < 250) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Payment Breakdown', 14, yPos);

    autoTable(doc, {
      startY: yPos + 5,
      head: [['Payment Type', 'Amount']],
      body: data.payments.map(p => [p.type, p.amount]),
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
    });
  }

  // Footer
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by DMS v2.2.5 - Created by Vishal Dhangar', 105, 285, { align: 'center' });

  // Save
  doc.save(`Report-${data.dateRange.replace(/\s/g, '-')}.pdf`);
}

export function exportBillToPDF(data: BillData) {
  const doc = new jsPDF();

  // Shop Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(data.shopName || 'Dairy Shop', 105, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (data.shopPhone) {
    doc.text(`Phone: ${data.shopPhone}`, 105, 27, { align: 'center' });
  }
  if (data.shopAddress) {
    doc.text(data.shopAddress, 105, 33, { align: 'center' });
  }

  // Bill Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('CUSTOMER BILL', 105, 45, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${data.date}`, 14, 55);

  // Customer Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 14, 65);
  doc.setFont('helvetica', 'normal');
  doc.text(data.customerName, 14, 72);
  if (data.customerPhone) {
    doc.text(`Phone: ${data.customerPhone}`, 14, 78);
  }
  if (data.customerAddress) {
    doc.text(data.customerAddress, 14, 84);
  }

  // Items Table
  autoTable(doc, {
    startY: 95,
    head: [['Item', 'Qty', 'Price', 'Total']],
    body: data.items.map(item => [
      item.name,
      item.quantity.toString(),
      `Rs. ${item.price}`,
      `Rs. ${item.total}`,
    ]),
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // Totals
  doc.setFontSize(12);
  doc.text(`Total Amount: Rs. ${data.totalAmount}`, 140, finalY, { align: 'right' });
  doc.text(`Paid Amount: Rs. ${data.paidAmount}`, 140, finalY + 7, { align: 'right' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(`Due Amount: Rs. ${data.dueAmount}`, 140, finalY + 16, { align: 'right' });

  // Footer
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text('Thank you for your business!', 105, finalY + 35, { align: 'center' });
  doc.text('Generated by DMS v2.2.5', 105, 285, { align: 'center' });

  // Save
  doc.save(`Bill-${data.customerName.replace(/\s/g, '-')}-${data.date}.pdf`);
}

// New Professional Monthly Bill Export for Fixed Customers
export function exportMonthlyBillToPDF(data: MonthlyBillData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ===== HEADER SECTION =====
  // Shop Header with border
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(1);
  doc.rect(10, 10, pageWidth - 20, 35, 'S');

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(59, 130, 246);
  doc.text(data.shopName || 'Dairy Shop', pageWidth / 2, 22, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  if (data.shopPhone) {
    doc.text(`Phone: ${data.shopPhone}`, pageWidth / 2, 30, { align: 'center' });
  }
  if (data.shopAddress) {
    doc.text(data.shopAddress, pageWidth / 2, 37, { align: 'center' });
  }

  // ===== BILL TITLE =====
  doc.setFillColor(59, 130, 246);
  doc.rect(10, 50, pageWidth - 20, 10, 'F');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('MONTHLY STATEMENT', pageWidth / 2, 57, { align: 'center' });

  // Month
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.text(`Month: ${data.month}`, pageWidth / 2, 70, { align: 'center' });

  // ===== CUSTOMER SECTION =====
  doc.setFillColor(245, 245, 245);
  doc.rect(10, 75, pageWidth - 20, 25, 'F');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Customer Details', 14, 83);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${data.customerName}`, 14, 91);
  doc.text(`Phone: ${data.customerPhone || 'N/A'}`, pageWidth / 2, 91);
  if (data.customerAddress) {
    doc.text(`Address: ${data.customerAddress}`, 14, 97);
  }

  // ===== PREVIOUS BALANCE =====
  let yPos = 108;
  doc.setFillColor(255, 243, 224);
  doc.rect(10, yPos - 5, pageWidth - 20, 12, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(200, 100, 0);
  doc.text('Previous Balance (Due from last month):', 14, yPos + 3);
  doc.text(`Rs. ${data.previousBalance}`, pageWidth - 14, yPos + 3, { align: 'right' });

  // ===== DELIVERIES TABLE =====
  yPos = 125;
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('This Month\'s Deliveries', 14, yPos);

  // Build delivery rows with items
  const deliveryRows: (string | number)[][] = [];
  data.deliveries.forEach(delivery => {
    // Format items as string
    const itemsStr = delivery.items.map(i => `${i.name} x${i.quantity}`).join(', ');
    const paidStr = delivery.paidAtDelivery > 0 ? `Paid: Rs.${delivery.paidAtDelivery}` : 'Due';
    deliveryRows.push([
      delivery.date,
      itemsStr,
      `Rs. ${delivery.total}`,
      paidStr
    ]);
  });

  if (deliveryRows.length > 0) {
    autoTable(doc, {
      startY: yPos + 5,
      head: [['Date', 'Items', 'Amount', 'Payment']],
      body: deliveryRows,
      theme: 'striped',
      headStyles: { fillColor: [59, 130, 246], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 30, halign: 'right' },
        3: { cellWidth: 30, halign: 'center' },
      },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  } else {
    yPos += 10;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.text('No deliveries this month', 14, yPos);
    yPos += 10;
  }

  // Monthly Total Row
  doc.setFillColor(230, 245, 255);
  doc.rect(10, yPos - 3, pageWidth - 20, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text('This Month Total:', 14, yPos + 4);
  doc.text(`Rs. ${data.monthlyTotal}`, pageWidth - 14, yPos + 4, { align: 'right' });

  // ===== PAYMENTS RECEIVED TABLE =====
  yPos += 20;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Payments Received', 14, yPos);

  if (data.payments.length > 0) {
    const paymentRows = data.payments.map(p => [
      p.date,
      p.mode === 'cash' ? 'Cash' : 'Online',
      `Rs. ${p.amount}`
    ]);

    autoTable(doc, {
      startY: yPos + 5,
      head: [['Date', 'Mode', 'Amount']],
      body: paymentRows,
      theme: 'striped',
      headStyles: { fillColor: [34, 197, 94], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 40 },
        2: { cellWidth: 'auto', halign: 'right' },
      },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  } else {
    yPos += 10;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.text('No payments received this month', 14, yPos);
    yPos += 10;
  }

  // Total Payments Row
  doc.setFillColor(220, 252, 231);
  doc.rect(10, yPos - 3, pageWidth - 20, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(0, 100, 0);
  doc.text('Total Payments:', 14, yPos + 4);
  doc.text(`Rs. ${data.totalPayments}`, pageWidth - 14, yPos + 4, { align: 'right' });

  // ===== FINAL SUMMARY BOX =====
  yPos += 20;
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(1.5);
  doc.rect(10, yPos - 5, pageWidth - 20, 45, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('ACCOUNT SUMMARY', pageWidth / 2, yPos + 3, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const summaryY = yPos + 12;
  doc.text('Previous Balance:', 20, summaryY);
  doc.text(`Rs. ${data.previousBalance}`, pageWidth - 20, summaryY, { align: 'right' });

  doc.text('(+) This Month Items:', 20, summaryY + 7);
  doc.text(`Rs. ${data.monthlyTotal}`, pageWidth - 20, summaryY + 7, { align: 'right' });

  doc.text('(-) Payments Received:', 20, summaryY + 14);
  doc.setTextColor(0, 150, 0);
  doc.text(`Rs. ${data.totalPayments}`, pageWidth - 20, summaryY + 14, { align: 'right' });

  // Draw line before balance
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(120, summaryY + 18, pageWidth - 20, summaryY + 18);

  // Balance Due (highlighted)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  if (data.balanceDue > 0) {
    doc.setTextColor(200, 0, 0);
  } else {
    doc.setTextColor(0, 150, 0);
  }
  doc.text('Balance Due:', 20, summaryY + 26);
  doc.text(`Rs. ${data.balanceDue}`, pageWidth - 20, summaryY + 26, { align: 'right' });

  // ===== FOOTER =====
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 100, 100);
  doc.text('Thank you for your business!', pageWidth / 2, 275, { align: 'center' });
  doc.text('Generated by DMS v2.2.5 - Dairy Management System', pageWidth / 2, 282, { align: 'center' });

  // Save
  const fileName = `MonthlyBill-${data.customerName.replace(/\s/g, '-')}-${data.month.replace(/\s/g, '-')}.pdf`;
  doc.save(fileName);
}
